SELECT * from customer

-- Q1. Total revenue generated by male vs female customers
--------------------------------------------------------------
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

-- Q2. Customers who used a discount but spent more 
--     than the average purchase amount
--------------------------------------------------------------
WITH avg_purchase AS (
    SELECT AVG(purchase_amount) AS avg_amt FROM customer
)
SELECT customer_id, purchase_amount
FROM customer, avg_purchase
WHERE discount_applied = 'Yes'
  AND purchase_amount > avg_amt;

--------------------------------------------------------------
-- Q3. Top 5 products with the highest average review rating
--------------------------------------------------------------
SELECT item_purchased, ROUND(AVG(review_rating)::numeric,2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

--------------------------------------------------------------
-- Q4. Compare average purchase amounts between 
--     Standard and Express Shipping
--------------------------------------------------------------
SELECT shipping_type, ROUND(AVG(purchase_amount)::numeric,2) AS avg_purchase
FROM customer
GROUP BY shipping_type;

--------------------------------------------------------------
-- Q5. Compare average spend & total revenue between 
--     subscribers and non-subscribers
--------------------------------------------------------------
SELECT subscription_status,
       ROUND(AVG(purchase_amount)::numeric,2) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

--------------------------------------------------------------
-- Q6. 5 products with highest percentage of purchases 
--     made with discounts
--------------------------------------------------------------
SELECT item_purchased,
       COUNT(*) FILTER (WHERE discount_applied = 'Yes')::DECIMAL 
       / COUNT(*) * 100 AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

--------------------------------------------------------------
-- Q7. Segment customers into:
--     New = 0 purchases
--     Returning = 1–5 purchases
--     Loyal = >5 purchases
--------------------------------------------------------------
WITH customer_segments AS (
    SELECT customer_id,
           CASE 
               WHEN previous_purchases = 0 THEN 'New'
               WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
               WHEN previous_purchases > 5 THEN 'Loyal'
           END AS segment
    FROM customer
)
SELECT segment, COUNT(*) AS customer_count
FROM customer_segments
GROUP BY segment;

--------------------------------------------------------------
-- Q8. Top 3 most purchased products within each category
--------------------------------------------------------------
SELECT category, item_purchased, purchase_count
FROM (
    SELECT category, item_purchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rn
    FROM customer
    GROUP BY category, item_purchased
) ranked
WHERE rn <= 3
ORDER BY category, purchase_count DESC;

--------------------------------------------------------------
-- Q9. Are repeat buyers (>5 previous purchases) 
--     more likely to subscribe?
--------------------------------------------------------------
SELECT
    CASE WHEN previous_purchases > 5 THEN 'Repeat Buyer' ELSE 'Non-Repeat' END AS buyer_type,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribers
FROM customer
GROUP BY buyer_type;

--------------------------------------------------------------
-- Q10. Revenue contribution of each age group
--------------------------------------------------------------
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;